// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

using System.Text;

namespace Apache.Iggy.Tools.ErrorCodeGenerator;

/// <summary>
///     Generates C# code for IggyErrorCode enum and extensions.
/// </summary>
public static class CSharpCodeGenerator
{
    /// <summary>
    ///     Converts license file content to C# comment format.
    /// </summary>
    public static string ConvertLicenseToComments(string licenseContent)
    {
        var sb = new StringBuilder();
        var lines = licenseContent.Split('\n');

        foreach (var line in lines)
        {
            var trimmedLine = line.TrimEnd('\r');
            if (string.IsNullOrWhiteSpace(trimmedLine))
            {
                sb.AppendLine("//");
            }
            else
            {
                sb.AppendLine($"// {trimmedLine}");
            }
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private const string GeneratedHeader = """
        // <auto-generated>
        //     This code was generated by iggy-error-codegen tool.
        //     Do not modify this file manually.
        //     To regenerate, run: dotnet iggy-error-codegen generate
        // </auto-generated>

        """;

    /// <summary>
    ///     Generates the IggyErrorCode.cs enum file content.
    /// </summary>
    /// <param name="errors">List of error codes parsed from Rust.</param>
    /// <param name="license">License header to include in the generated file.</param>
    public static string GenerateEnum(List<RustErrorCode> errors, string license)
    {
        var sb = new StringBuilder();
        sb.Append(license);
        sb.Append(GeneratedHeader);
        sb.AppendLine("namespace Apache.Iggy.Enums;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Error codes returned by the Iggy server.");
        sb.AppendLine("///     These codes match the error codes defined in the Rust server implementation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public enum IggyErrorCode");
        sb.AppendLine("{");

        foreach (var error in errors.OrderBy(e => e.Code))
        {
            // Clean up message for XML comment
            var xmlSafeMessage = error.Message
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("{0}", "")
                .Replace("{1}", "")
                .Replace("{2}", "")
                .Replace("  ", " ")
                .Trim();

            sb.AppendLine($"    /// <summary>{xmlSafeMessage}</summary>");
            sb.AppendLine($"    {error.Name} = {error.Code},");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Generates the IggyErrorCodeExtensions.cs file content.
    /// </summary>
    /// <param name="errors">List of error codes parsed from Rust.</param>
    /// <param name="license">License header to include in the generated file.</param>
    public static string GenerateExtensions(List<RustErrorCode> errors, string license)
    {
        var sb = new StringBuilder();
        sb.Append(license);
        sb.Append(GeneratedHeader);
        sb.AppendLine("namespace Apache.Iggy.Enums;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Extension methods for <see cref=\"IggyErrorCode\"/> to categorize and check error types.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class IggyErrorCodeExtensions");
        sb.AppendLine("{");

        // Generate category methods
        foreach (var category in ErrorCategories.Categories)
        {
            var matchingErrors = errors.Where(e => category.Value(e.Name)).ToList();
            if (matchingErrors.Count == 0) continue;

            var methodName = category.Key;
            var description = GetCategoryDescription(methodName);

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    ///     {description}");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static bool {methodName}(this IggyErrorCode code) => code switch");
            sb.AppendLine("    {");

            foreach (var error in matchingErrors.OrderBy(e => e.Code))
            {
                sb.AppendLine($"        IggyErrorCode.{error.Name} => true,");
            }

            sb.AppendLine("        _ => false");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        // Generate TryFromStatusCode method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Tries to convert an integer status code to <see cref=\"IggyErrorCode\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"statusCode\">The integer status code.</param>");
        sb.AppendLine("    /// <param name=\"errorCode\">The resulting error code if conversion succeeds.</param>");
        sb.AppendLine("    /// <returns>True if the conversion succeeded, false otherwise.</returns>");
        sb.AppendLine("    public static bool TryFromStatusCode(int statusCode, out IggyErrorCode errorCode)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Enum.IsDefined(typeof(IggyErrorCode), statusCode))");
        sb.AppendLine("        {");
        sb.AppendLine("            errorCode = (IggyErrorCode)statusCode;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        errorCode = IggyErrorCode.Error;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate FromStatusCode method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Converts an integer status code to <see cref=\"IggyErrorCode\"/>.");
        sb.AppendLine("    ///     Returns <see cref=\"IggyErrorCode.Error\"/> if the code is not recognized.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"statusCode\">The integer status code.</param>");
        sb.AppendLine("    /// <returns>The corresponding error code or <see cref=\"IggyErrorCode.Error\"/> if not found.</returns>");
        sb.AppendLine("    public static IggyErrorCode FromStatusCode(int statusCode)");
        sb.AppendLine("    {");
        sb.AppendLine("        return TryFromStatusCode(statusCode, out var errorCode) ? errorCode : IggyErrorCode.Error;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetCategoryDescription(string methodName) => methodName switch
    {
        "IsNotFound" => "Checks if the error code indicates that a resource was not found.",
        "IsAlreadyExists" => "Checks if the error code indicates that a resource already exists.",
        "IsAuthenticationError" => "Checks if the error code is related to authentication.",
        "IsConnectionError" => "Checks if the error code is related to connection issues.",
        "IsStreamError" => "Checks if the error code is related to streams.",
        "IsTopicError" => "Checks if the error code is related to topics.",
        "IsConsumerGroupError" => "Checks if the error code is related to consumer groups.",
        "IsMessageError" => "Checks if the error code is related to messages.",
        "IsUserError" => "Checks if the error code is related to user management.",
        "IsPersonalAccessTokenError" => "Checks if the error code is related to personal access tokens.",
        "IsTlsError" => "Checks if the error code is related to TLS/certificates.",
        "IsValidationError" => "Checks if the error code indicates a validation error.",
        "IsLimitReached" => "Checks if the error code indicates a limit has been reached.",
        _ => $"Checks if the error code matches the {methodName} category."
    };
}
