// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// <auto-generated>
//     This code was generated by iggy-error-codegen tool.
//     Do not modify this file manually.
//     To regenerate, run: dotnet iggy-error-codegen generate
// </auto-generated>
namespace Apache.Iggy.Enums;

/// <summary>
///     Error codes returned by the Iggy server.
///     These codes match the error codes defined in the Rust server implementation.
/// </summary>
public enum IggyErrorCode
{
    /// <summary>Error</summary>
    Error = 1,

    /// <summary>Invalid configuration</summary>
    InvalidConfiguration = 2,

    /// <summary>Invalid command</summary>
    InvalidCommand = 3,

    /// <summary>Invalid format</summary>
    InvalidFormat = 4,

    /// <summary>Feature is unavailable</summary>
    FeatureUnavailable = 5,

    /// <summary>Invalid identifier</summary>
    InvalidIdentifier = 6,

    /// <summary>Invalid version: {0}</summary>
    InvalidVersion = 7,

    /// <summary>Disconnected</summary>
    Disconnected = 8,

    /// <summary>Cannot establish connection</summary>
    CannotEstablishConnection = 9,

    /// <summary>Cannot create base directory, Path: {0}</summary>
    CannotCreateBaseDirectory = 10,

    /// <summary>Cannot create runtime directory, Path: {0}</summary>
    CannotCreateRuntimeDirectory = 11,

    /// <summary>Cannot remove runtime directory, Path: {0}</summary>
    CannotRemoveRuntimeDirectory = 12,

    /// <summary>Cannot create state directory, Path: {0}</summary>
    CannotCreateStateDirectory = 13,

    /// <summary>State file not found</summary>
    StateFileNotFound = 14,

    /// <summary>State file corrupted</summary>
    StateFileCorrupted = 15,

    /// <summary>Invalid state entry checksum: {0}, expected: {1}, for index: {2}</summary>
    InvalidStateEntryChecksum = 16,

    /// <summary>Cannot open database, Path: {0}</summary>
    CannotOpenDatabase = 19,

    /// <summary>Resource with key: {0} was not found.</summary>
    ResourceNotFound = 20,

    /// <summary>Cannot close WebSocket connection</summary>
    CannotCloseWebSocketConnection = 21,

    /// <summary>Stale client</summary>
    StaleClient = 30,

    /// <summary>TCP error</summary>
    TcpError = 31,

    /// <summary>QUIC error</summary>
    QuicError = 32,

    /// <summary>Invalid server address</summary>
    InvalidServerAddress = 33,

    /// <summary>Invalid client address</summary>
    InvalidClientAddress = 34,

    /// <summary>Invalid IP address: {0}:{1}</summary>
    InvalidIpAddress = 35,

    /// <summary>Http error {0}</summary>
    HttpError = 36,

    /// <summary>Unauthenticated</summary>
    Unauthenticated = 40,

    /// <summary>Unauthorized</summary>
    Unauthorized = 41,

    /// <summary>Invalid credentials</summary>
    InvalidCredentials = 42,

    /// <summary>Invalid username</summary>
    InvalidUsername = 43,

    /// <summary>Invalid password</summary>
    InvalidPassword = 44,

    /// <summary>Invalid user status</summary>
    InvalidUserStatus = 45,

    /// <summary>User already exists</summary>
    UserAlreadyExists = 46,

    /// <summary>User inactive</summary>
    UserInactive = 47,

    /// <summary>Cannot delete user with ID: {0}</summary>
    CannotDeleteUser = 48,

    /// <summary>Cannot change permissions for user with ID: {0}</summary>
    CannotChangePermissions = 49,

    /// <summary>Invalid personal access token name</summary>
    InvalidPersonalAccessTokenName = 50,

    /// <summary>Personal access token: {0} for user with ID: {1} already exists</summary>
    PersonalAccessTokenAlreadyExists = 51,

    /// <summary>User with ID: {0} has reached the maximum number of personal access tokens: {1}</summary>
    PersonalAccessTokensLimitReached = 52,

    /// <summary>Invalid personal access token</summary>
    InvalidPersonalAccessToken = 53,

    /// <summary>Personal access token: {0} for user with ID: {1} has expired.</summary>
    PersonalAccessTokenExpired = 54,

    /// <summary>Users limit reached.</summary>
    UsersLimitReached = 55,

    /// <summary>Not connected</summary>
    NotConnected = 61,

    /// <summary>Client shutdown</summary>
    ClientShutdown = 63,

    /// <summary>Invalid TLS domain</summary>
    InvalidTlsDomain = 64,

    /// <summary>Invalid TLS certificate path</summary>
    InvalidTlsCertificatePath = 65,

    /// <summary>Invalid TLS certificate</summary>
    InvalidTlsCertificate = 66,

    /// <summary>Failed to add certificate</summary>
    FailedToAddCertificate = 67,

    /// <summary>Invalid encryption key</summary>
    InvalidEncryptionKey = 70,

    /// <summary>Cannot encrypt data</summary>
    CannotEncryptData = 71,

    /// <summary>Cannot decrypt data</summary>
    CannotDecryptData = 72,

    /// <summary>Invalid JWT algorithm: {0}</summary>
    InvalidJwtAlgorithm = 73,

    /// <summary>Invalid JWT secret</summary>
    InvalidJwtSecret = 74,

    /// <summary>JWT is missing</summary>
    JwtMissing = 75,

    /// <summary>Cannot generate JWT</summary>
    CannotGenerateJwt = 76,

    /// <summary>Access token is missing</summary>
    AccessTokenMissing = 77,

    /// <summary>Invalid access token</summary>
    InvalidAccessToken = 78,

    /// <summary>Invalid size bytes</summary>
    InvalidSizeBytes = 80,

    /// <summary>Invalid UTF-8</summary>
    InvalidUtf8 = 81,

    /// <summary>Invalid number encoding</summary>
    InvalidNumberEncoding = 82,

    /// <summary>Invalid boolean value</summary>
    InvalidBooleanValue = 83,

    /// <summary>Invalid number value</summary>
    InvalidNumberValue = 84,

    /// <summary>Client with ID: {0} was not found.</summary>
    ClientNotFound = 100,

    /// <summary>Invalid client ID</summary>
    InvalidClientId = 101,

    /// <summary>Connection closed</summary>
    ConnectionClosed = 206,

    /// <summary>Cannot parse header kind from {0}</summary>
    CannotParseHeaderKind = 209,

    /// <summary>HTTP response error, status: {0}, body: {1}</summary>
    HttpResponseError = 300,

    /// <summary>Invalid HTTP request</summary>
    InvalidHttpRequest = 301,

    /// <summary>Invalid JSON response</summary>
    InvalidJsonResponse = 302,

    /// <summary>Invalid bytes response</summary>
    InvalidBytesResponse = 303,

    /// <summary>Empty response</summary>
    EmptyResponse = 304,

    /// <summary>Cannot create endpoint</summary>
    CannotCreateEndpoint = 305,

    /// <summary>Cannot parse URL</summary>
    CannotParseUrl = 306,

    /// <summary>WebSocket error</summary>
    WebSocketError = 400,

    /// <summary>WebSocket connection error</summary>
    WebSocketConnectionError = 401,

    /// <summary>WebSocket close error</summary>
    WebSocketCloseError = 402,

    /// <summary>WebSocket receive error</summary>
    WebSocketReceiveError = 403,

    /// <summary>WebSocket send error</summary>
    WebSocketSendError = 404,

    /// <summary>Cannot create streams directory, Path: {0}</summary>
    CannotCreateStreamsDirectory = 1000,

    /// <summary>Cannot create stream with ID: {0} directory, Path: {1}</summary>
    CannotCreateStreamDirectory = 1001,

    /// <summary>Failed to create stream info file for stream with ID: {0}</summary>
    CannotCreateStreamInfo = 1002,

    /// <summary>Failed to update stream info for stream with ID: {0}</summary>
    CannotUpdateStreamInfo = 1003,

    /// <summary>Failed to open stream info file for stream with ID: {0}</summary>
    CannotOpenStreamInfo = 1004,

    /// <summary>Failed to read stream info file for stream with ID: {0}</summary>
    CannotReadStreamInfo = 1005,

    /// <summary>Failed to create stream with ID: {0}</summary>
    CannotCreateStream = 1006,

    /// <summary>Failed to delete stream with ID: {0}</summary>
    CannotDeleteStream = 1007,

    /// <summary>Failed to delete stream directory with ID: {0}</summary>
    CannotDeleteStreamDirectory = 1008,

    /// <summary>Stream with ID: {0} was not found.</summary>
    StreamIdNotFound = 1009,

    /// <summary>Stream with name: {0} was not found.</summary>
    StreamNameNotFound = 1010,

    /// <summary>Stream with directory {0} was not found.</summary>
    StreamDirectoryNotFound = 1011,

    /// <summary>Stream with name: {0} already exists.</summary>
    StreamNameAlreadyExists = 1012,

    /// <summary>Invalid stream name</summary>
    InvalidStreamName = 1013,

    /// <summary>Invalid stream ID</summary>
    InvalidStreamId = 1014,

    /// <summary>Cannot read streams</summary>
    CannotReadStreams = 1015,

    /// <summary>Cannot create topics directory for stream with ID: {0}, Path: {1}</summary>
    CannotCreateTopicsDirectory = 2000,

    /// <summary>Failed to create directory for topic with ID: {0} for stream with ID: {1}, Path: {2}</summary>
    CannotCreateTopicDirectory = 2001,

    /// <summary>Failed to create topic info file for topic with ID: {0} for stream with ID: {1}.</summary>
    CannotCreateTopicInfo = 2002,

    /// <summary>Failed to update topic info for topic with ID: {0} for stream with ID: {1}.</summary>
    CannotUpdateTopicInfo = 2003,

    /// <summary>Failed to open topic info file for topic with ID: {0} for stream with ID: {1}.</summary>
    CannotOpenTopicInfo = 2004,

    /// <summary>Failed to read topic info file for topic with ID: {0} for stream with ID: {1}.</summary>
    CannotReadTopicInfo = 2005,

    /// <summary>Failed to create topic with ID: {0} for stream with ID: {1}.</summary>
    CannotCreateTopic = 2006,

    /// <summary>Failed to delete topic with ID: {0} for stream with ID: {1}.</summary>
    CannotDeleteTopic = 2007,

    /// <summary>Failed to delete topic directory with ID: {0} for stream with ID: {1}, Path: {2}</summary>
    CannotDeleteTopicDirectory = 2008,

    /// <summary>Cannot poll topic</summary>
    CannotPollTopic = 2009,

    /// <summary>Topic with ID: {0} for stream with ID: {1} was not found.</summary>
    TopicIdNotFound = 2010,

    /// <summary>Topic with name: {0} for stream with ID: {1} was not found.</summary>
    TopicNameNotFound = 2011,

    /// <summary>Topic with name: {0} for stream with ID: {1} already exists.</summary>
    TopicNameAlreadyExists = 2013,

    /// <summary>Invalid topic name</summary>
    InvalidTopicName = 2014,

    /// <summary>Too many partitions</summary>
    TooManyPartitions = 2015,

    /// <summary>Invalid topic ID</summary>
    InvalidTopicId = 2016,

    /// <summary>Cannot read topics for stream with ID: {0}</summary>
    CannotReadTopics = 2017,

    /// <summary>Invalid replication factor</summary>
    InvalidReplicationFactor = 2018,

    /// <summary>Invalid partitions count</summary>
    InvalidPartitionsCount = 2019,

    /// <summary>Topic directory: {0} not found</summary>
    TopicDirectoryNotFound = 2020,

    /// <summary>Cannot create partition with ID: {0} for stream with ID: {1} and topic with ID: {2}</summary>
    CannotCreatePartition = 3000,

    /// <summary>Cannot open partition log file</summary>
    CannotOpenPartitionLogFile = 3003,

    /// <summary>Cannot read partitions directories.</summary>
    CannotReadPartitions = 3004,

    /// <summary>Partition with ID: {0} for topic with ID: {1} for stream with ID: {2} was not found.</summary>
    PartitionNotFound = 3007,

    /// <summary>Topic with ID: {0} for stream with ID: {1} has no partitions.</summary>
    NoPartitions = 3008,

    /// <summary>Cannot read partitions for topic with ID: {0} for stream with ID: {1}</summary>
    TopicFull = 3009,

    /// <summary>Failed to delete consumer offsets directory for path: {0}</summary>
    CannotDeleteConsumerOffsetsDirectory = 3010,

    /// <summary>Failed to delete consumer offset file for path: {0}</summary>
    CannotDeleteConsumerOffsetFile = 3011,

    /// <summary>Failed to create consumer offsets directory for path: {0}</summary>
    CannotCreateConsumerOffsetsDirectory = 3012,

    /// <summary>Failed to read consumers offsets from path: {0}</summary>
    CannotReadConsumerOffsets = 3020,

    /// <summary>Consumer offset for consumer with ID: {0} was not found.</summary>
    ConsumerOffsetNotFound = 3021,

    /// <summary>Failed to resolve consumer with ID: {0}</summary>
    NotResolvedConsumer = 3022,

    /// <summary>Cannot open consumer offsets file for path: {0}</summary>
    CannotOpenConsumerOffsetsFile = 3023,

    /// <summary>Segment not found</summary>
    SegmentNotFound = 4000,

    /// <summary>Segment with start offset: {0} and partition with ID: {1} is closed</summary>
    SegmentClosed = 4001,

    /// <summary>Segment size is invalid</summary>
    InvalidSegmentSize = 4002,

    /// <summary>Failed to create segment log file for Path: {0}.</summary>
    CannotCreateSegmentLogFile = 4003,

    /// <summary>Failed to create segment index file for Path: {0}.</summary>
    CannotCreateSegmentIndexFile = 4004,

    /// <summary>Failed to create segment time index file for Path: {0}.</summary>
    CannotCreateSegmentTimeIndexFile = 4005,

    /// <summary>Cannot save messages to segment.</summary>
    CannotSaveMessagesToSegment = 4006,

    /// <summary>Cannot save index to segment.</summary>
    CannotSaveIndexToSegment = 4007,

    /// <summary>Cannot save time index to segment.</summary>
    CannotSaveTimeIndexToSegment = 4008,

    /// <summary>Invalid messages count</summary>
    InvalidMessagesCount = 4009,

    /// <summary>Cannot append message</summary>
    CannotAppendMessage = 4010,

    /// <summary>Cannot read message</summary>
    CannotReadMessage = 4011,

    /// <summary>Cannot read message ID</summary>
    CannotReadMessageId = 4012,

    /// <summary>Cannot read message state</summary>
    CannotReadMessageState = 4013,

    /// <summary>Cannot read message timestamp</summary>
    CannotReadMessageTimestamp = 4014,

    /// <summary>Cannot read headers length</summary>
    CannotReadHeadersLength = 4015,

    /// <summary>Cannot read headers payload</summary>
    CannotReadHeadersPayload = 4016,

    /// <summary>Too big headers payload</summary>
    TooBigUserHeaders = 4017,

    /// <summary>Invalid header key</summary>
    InvalidHeaderKey = 4018,

    /// <summary>Invalid header value</summary>
    InvalidHeaderValue = 4019,

    /// <summary>Cannot read message length</summary>
    CannotReadMessageLength = 4020,

    /// <summary>Cannot save messages to segment</summary>
    CannotReadMessagePayload = 4021,

    /// <summary>Too big message payload</summary>
    TooBigMessagePayload = 4022,

    /// <summary>Too many messages</summary>
    TooManyMessages = 4023,

    /// <summary>Empty message payload</summary>
    EmptyMessagePayload = 4024,

    /// <summary>Invalid message payload length</summary>
    InvalidMessagePayloadLength = 4025,

    /// <summary>Cannot read message checksum</summary>
    CannotReadMessageChecksum = 4026,

    /// <summary>Invalid message checksum: {0}, expected: {1}, for offset: {2}</summary>
    InvalidMessageChecksum = 4027,

    /// <summary>Invalid key value length</summary>
    InvalidKeyValueLength = 4028,

    /// <summary>Command length error: {0}</summary>
    CommandLengthError = 4029,

    /// <summary>Incorrect Segments Count size: {0}</summary>
    InvalidSegmentsCount = 4030,

    /// <summary>Non-zero offset: {0} at index: {1}</summary>
    NonZeroOffset = 4031,

    /// <summary>Non-zero timestamp: {0} at index: {1}</summary>
    NonZeroTimestamp = 4032,

    /// <summary>Missing index: {0}</summary>
    MissingIndex = 4033,

    /// <summary>Invalid indexes byte size: {0}B, should be divisible by 16</summary>
    InvalidIndexesByteSize = 4034,

    /// <summary>Invalid indexes count: {0}, expected: {1}</summary>
    InvalidIndexesCount = 4035,

    /// <summary>Invalid messages byte size: {0}B, expected: {1}B</summary>
    InvalidMessagesSize = 4036,

    /// <summary>Too small message: {0}B, expected: {1}B</summary>
    TooSmallMessage = 4037,

    /// <summary>Cannot sed messages due to client disconnection</summary>
    CannotSendMessagesDueToClientDisconnection = 4050,

    /// <summary>Background send error</summary>
    BackgroundSendError = 4051,

    /// <summary>Background send timeout</summary>
    BackgroundSendTimeout = 4052,

    /// <summary>Background send buffer is full</summary>
    BackgroundSendBufferFull = 4053,

    /// <summary>Background worker disconnected</summary>
    BackgroundWorkerDisconnected = 4054,

    /// <summary>Background send buffer overflow</summary>
    BackgroundSendBufferOverflow = 4055,

    /// <summary>Producer closed</summary>
    ProducerClosed = 4057,

    /// <summary>Invalid offset: {0}</summary>
    InvalidOffset = 4100,

    /// <summary>Consumer group with ID: {0} for topic with ID: {1} was not found.</summary>
    ConsumerGroupIdNotFound = 5000,

    /// <summary>Invalid consumer group ID</summary>
    InvalidConsumerGroupId = 5002,

    /// <summary>Consumer group with name: {0} for topic with ID: {1} was not found.</summary>
    ConsumerGroupNameNotFound = 5003,

    /// <summary>Consumer group with name: {0} for topic with ID: {1} already exists.</summary>
    ConsumerGroupNameAlreadyExists = 5004,

    /// <summary>Invalid consumer group name</summary>
    InvalidConsumerGroupName = 5005,

    /// <summary>Base offset is missing</summary>
    MissingBaseOffsetRetainedMessageBatch = 6000,

    /// <summary>Last offset delta is missing</summary>
    MissingLastOffsetDeltaRetainedMessageBatch = 6001,

    /// <summary>Max timestamp is missing</summary>
    MissingMaxTimestampRetainedMessageBatch = 6002,

    /// <summary>Length is missing</summary>
    MissingLengthRetainedMessageBatch = 6003,

    /// <summary>Payload is missing</summary>
    MissingPayloadRetainedMessageBatch = 6004,

    /// <summary>Cannot read batch base offset</summary>
    CannotReadBatchBaseOffset = 7000,

    /// <summary>Cannot read batch length</summary>
    CannotReadBatchLength = 7001,

    /// <summary>Cannot read batch last offset delta</summary>
    CannotReadLastOffsetDelta = 7002,

    /// <summary>Cannot read batch maximum timestamp</summary>
    CannotReadMaxTimestamp = 7003,

    /// <summary>Cannot read batch payload</summary>
    CannotReadBatchPayload = 7004,

    /// <summary>Invalid connection string</summary>
    InvalidConnectionString = 8000,

    /// <summary>Snapshot file completion failed</summary>
    SnapshotFileCompletionFailed = 9000,

    /// <summary>Cannot serialize resource</summary>
    CannotSerializeResource = 10000,

    /// <summary>Cannot deserialize resource</summary>
    CannotDeserializeResource = 10001,

    /// <summary>Cannot read file</summary>
    CannotReadFile = 10002,

    /// <summary>Cannot read file metadata</summary>
    CannotReadFileMetadata = 10003,

    /// <summary>Cannot seek file</summary>
    CannotSeekFile = 10004,

    /// <summary>Cannot append to file</summary>
    CannotAppendToFile = 10005,

    /// <summary>Cannot write to file</summary>
    CannotWriteToFile = 10006,

    /// <summary>Cannot overwrite file</summary>
    CannotOverwriteFile = 10007,

    /// <summary>Cannot delete file</summary>
    CannotDeleteFile = 10008,

    /// <summary>Cannot sync file</summary>
    CannotSyncFile = 10009,

    /// <summary>Cannot read index offset</summary>
    CannotReadIndexOffset = 10010,

    /// <summary>Cannot read index position</summary>
    CannotReadIndexPosition = 10011,

    /// <summary>Cannot read index timestamp</summary>
    CannotReadIndexTimestamp = 10012,

    /// <summary>Timestamp out of range: {0}</summary>
    TimestampOutOfRange = 10013,

    /// <summary>Shard not found for stream ID: {0}, topic ID: {1}, partition ID: {2}</summary>
    ShardNotFound = 11000,

    /// <summary>Shard communication error</summary>
    ShardCommunicationError = 11001,

    /// <summary>Cannot bind to socket with addr: {0}</summary>
    CannotBindToSocket = 12000,

    /// <summary>Task execution timeout</summary>
    TaskTimeout = 12001,

    /// <summary>IO error: {0}</summary>
    IoError = 13000,

}
