// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// <auto-generated>
//     This code was generated by iggy-error-codegen tool.
//     Do not modify this file manually.
//     To regenerate, run: dotnet iggy-error-codegen generate
// </auto-generated>

namespace Apache.Iggy.Enums;

/// <summary>
///     Extension methods for <see cref="IggyErrorCode" /> to categorize and check error types.
/// </summary>
public static class IggyErrorCodeExtensions
{
    /// <summary>
    ///     Checks if the error code indicates that a resource already exists.
    /// </summary>
    public static bool IsAlreadyExists(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.UserAlreadyExists => true,
        IggyErrorCode.PersonalAccessTokenAlreadyExists => true,
        IggyErrorCode.StreamNameAlreadyExists => true,
        IggyErrorCode.TopicNameAlreadyExists => true,
        IggyErrorCode.ConsumerGroupNameAlreadyExists => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to authentication.
    /// </summary>
    public static bool IsAuthenticationError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.Unauthenticated => true,
        IggyErrorCode.InvalidCredentials => true,
        IggyErrorCode.InvalidUsername => true,
        IggyErrorCode.InvalidPassword => true,
        IggyErrorCode.InvalidPersonalAccessToken => true,
        IggyErrorCode.PersonalAccessTokenExpired => true,
        IggyErrorCode.JwtMissing => true,
        IggyErrorCode.AccessTokenMissing => true,
        IggyErrorCode.InvalidAccessToken => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to connection issues.
    /// </summary>
    public static bool IsConnectionError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.Disconnected => true,
        IggyErrorCode.CannotEstablishConnection => true,
        IggyErrorCode.StaleClient => true,
        IggyErrorCode.TcpError => true,
        IggyErrorCode.QuicError => true,
        IggyErrorCode.NotConnected => true,
        IggyErrorCode.ClientShutdown => true,
        IggyErrorCode.ConnectionClosed => true,
        IggyErrorCode.WebSocketError => true,
        IggyErrorCode.WebSocketConnectionError => true,
        IggyErrorCode.WebSocketCloseError => true,
        IggyErrorCode.WebSocketReceiveError => true,
        IggyErrorCode.WebSocketSendError => true,
        IggyErrorCode.CannotSendMessagesDueToClientDisconnection => true,
        IggyErrorCode.BackgroundWorkerDisconnected => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to consumer groups.
    /// </summary>
    public static bool IsConsumerGroupError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.ConsumerGroupIdNotFound => true,
        IggyErrorCode.InvalidConsumerGroupId => true,
        IggyErrorCode.ConsumerGroupNameNotFound => true,
        IggyErrorCode.ConsumerGroupNameAlreadyExists => true,
        IggyErrorCode.InvalidConsumerGroupName => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code indicates a limit has been reached.
    /// </summary>
    public static bool IsLimitReached(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.PersonalAccessTokensLimitReached => true,
        IggyErrorCode.UsersLimitReached => true,
        IggyErrorCode.TooManyPartitions => true,
        IggyErrorCode.TopicFull => true,
        IggyErrorCode.TooBigUserHeaders => true,
        IggyErrorCode.TooBigMessagePayload => true,
        IggyErrorCode.TooManyMessages => true,
        IggyErrorCode.BackgroundSendBufferFull => true,
        IggyErrorCode.BackgroundSendBufferOverflow => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to messages.
    /// </summary>
    public static bool IsMessageError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.CannotParseHeaderKind => true,
        IggyErrorCode.CannotSaveMessagesToSegment => true,
        IggyErrorCode.InvalidMessagesCount => true,
        IggyErrorCode.CannotAppendMessage => true,
        IggyErrorCode.CannotReadMessage => true,
        IggyErrorCode.CannotReadMessageId => true,
        IggyErrorCode.CannotReadMessageState => true,
        IggyErrorCode.CannotReadMessageTimestamp => true,
        IggyErrorCode.CannotReadHeadersLength => true,
        IggyErrorCode.CannotReadHeadersPayload => true,
        IggyErrorCode.TooBigUserHeaders => true,
        IggyErrorCode.InvalidHeaderKey => true,
        IggyErrorCode.InvalidHeaderValue => true,
        IggyErrorCode.CannotReadMessageLength => true,
        IggyErrorCode.CannotReadMessagePayload => true,
        IggyErrorCode.TooBigMessagePayload => true,
        IggyErrorCode.TooManyMessages => true,
        IggyErrorCode.EmptyMessagePayload => true,
        IggyErrorCode.InvalidMessagePayloadLength => true,
        IggyErrorCode.CannotReadMessageChecksum => true,
        IggyErrorCode.InvalidMessageChecksum => true,
        IggyErrorCode.InvalidKeyValueLength => true,
        IggyErrorCode.InvalidMessagesSize => true,
        IggyErrorCode.TooSmallMessage => true,
        IggyErrorCode.CannotSendMessagesDueToClientDisconnection => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code indicates that a resource was not found.
    /// </summary>
    public static bool IsNotFound(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.StateFileNotFound => true,
        IggyErrorCode.ResourceNotFound => true,
        IggyErrorCode.ClientNotFound => true,
        IggyErrorCode.StreamIdNotFound => true,
        IggyErrorCode.StreamNameNotFound => true,
        IggyErrorCode.StreamDirectoryNotFound => true,
        IggyErrorCode.TopicIdNotFound => true,
        IggyErrorCode.TopicNameNotFound => true,
        IggyErrorCode.TopicDirectoryNotFound => true,
        IggyErrorCode.PartitionNotFound => true,
        IggyErrorCode.ConsumerOffsetNotFound => true,
        IggyErrorCode.SegmentNotFound => true,
        IggyErrorCode.ConsumerGroupIdNotFound => true,
        IggyErrorCode.ConsumerGroupNameNotFound => true,
        IggyErrorCode.ShardNotFound => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to personal access tokens.
    /// </summary>
    public static bool IsPersonalAccessTokenError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.InvalidPersonalAccessTokenName => true,
        IggyErrorCode.PersonalAccessTokenAlreadyExists => true,
        IggyErrorCode.PersonalAccessTokensLimitReached => true,
        IggyErrorCode.InvalidPersonalAccessToken => true,
        IggyErrorCode.PersonalAccessTokenExpired => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to streams.
    /// </summary>
    public static bool IsStreamError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.CannotCreateStreamsDirectory => true,
        IggyErrorCode.CannotCreateStreamDirectory => true,
        IggyErrorCode.CannotCreateStreamInfo => true,
        IggyErrorCode.CannotUpdateStreamInfo => true,
        IggyErrorCode.CannotOpenStreamInfo => true,
        IggyErrorCode.CannotReadStreamInfo => true,
        IggyErrorCode.CannotCreateStream => true,
        IggyErrorCode.CannotDeleteStream => true,
        IggyErrorCode.CannotDeleteStreamDirectory => true,
        IggyErrorCode.StreamIdNotFound => true,
        IggyErrorCode.StreamNameNotFound => true,
        IggyErrorCode.StreamDirectoryNotFound => true,
        IggyErrorCode.StreamNameAlreadyExists => true,
        IggyErrorCode.InvalidStreamName => true,
        IggyErrorCode.InvalidStreamId => true,
        IggyErrorCode.CannotReadStreams => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to TLS/certificates.
    /// </summary>
    public static bool IsTlsError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.InvalidTlsDomain => true,
        IggyErrorCode.InvalidTlsCertificatePath => true,
        IggyErrorCode.InvalidTlsCertificate => true,
        IggyErrorCode.FailedToAddCertificate => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to topics.
    /// </summary>
    public static bool IsTopicError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.CannotCreateTopicsDirectory => true,
        IggyErrorCode.CannotCreateTopicDirectory => true,
        IggyErrorCode.CannotCreateTopicInfo => true,
        IggyErrorCode.CannotUpdateTopicInfo => true,
        IggyErrorCode.CannotOpenTopicInfo => true,
        IggyErrorCode.CannotReadTopicInfo => true,
        IggyErrorCode.CannotCreateTopic => true,
        IggyErrorCode.CannotDeleteTopic => true,
        IggyErrorCode.CannotDeleteTopicDirectory => true,
        IggyErrorCode.CannotPollTopic => true,
        IggyErrorCode.TopicIdNotFound => true,
        IggyErrorCode.TopicNameNotFound => true,
        IggyErrorCode.TopicNameAlreadyExists => true,
        IggyErrorCode.InvalidTopicName => true,
        IggyErrorCode.TooManyPartitions => true,
        IggyErrorCode.InvalidTopicId => true,
        IggyErrorCode.CannotReadTopics => true,
        IggyErrorCode.InvalidReplicationFactor => true,
        IggyErrorCode.InvalidPartitionsCount => true,
        IggyErrorCode.TopicDirectoryNotFound => true,
        IggyErrorCode.TopicFull => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code is related to user management.
    /// </summary>
    public static bool IsUserError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.InvalidUsername => true,
        IggyErrorCode.InvalidPassword => true,
        IggyErrorCode.InvalidUserStatus => true,
        IggyErrorCode.UserAlreadyExists => true,
        IggyErrorCode.UserInactive => true,
        IggyErrorCode.CannotDeleteUser => true,
        IggyErrorCode.CannotChangePermissions => true,
        IggyErrorCode.UsersLimitReached => true,
        _ => false
    };

    /// <summary>
    ///     Checks if the error code indicates a validation error.
    /// </summary>
    public static bool IsValidationError(this IggyErrorCode code) => code switch
    {
        IggyErrorCode.InvalidConfiguration => true,
        IggyErrorCode.InvalidCommand => true,
        IggyErrorCode.InvalidFormat => true,
        IggyErrorCode.InvalidIdentifier => true,
        IggyErrorCode.InvalidVersion => true,
        IggyErrorCode.InvalidStateEntryChecksum => true,
        IggyErrorCode.InvalidServerAddress => true,
        IggyErrorCode.InvalidClientAddress => true,
        IggyErrorCode.InvalidIpAddress => true,
        IggyErrorCode.InvalidUsername => true,
        IggyErrorCode.InvalidPassword => true,
        IggyErrorCode.InvalidUserStatus => true,
        IggyErrorCode.InvalidTlsDomain => true,
        IggyErrorCode.InvalidTlsCertificatePath => true,
        IggyErrorCode.InvalidTlsCertificate => true,
        IggyErrorCode.InvalidEncryptionKey => true,
        IggyErrorCode.InvalidJwtAlgorithm => true,
        IggyErrorCode.InvalidJwtSecret => true,
        IggyErrorCode.InvalidSizeBytes => true,
        IggyErrorCode.InvalidUtf8 => true,
        IggyErrorCode.InvalidNumberEncoding => true,
        IggyErrorCode.InvalidBooleanValue => true,
        IggyErrorCode.InvalidNumberValue => true,
        IggyErrorCode.InvalidClientId => true,
        IggyErrorCode.InvalidHttpRequest => true,
        IggyErrorCode.InvalidJsonResponse => true,
        IggyErrorCode.InvalidBytesResponse => true,
        IggyErrorCode.InvalidStreamName => true,
        IggyErrorCode.InvalidStreamId => true,
        IggyErrorCode.InvalidTopicName => true,
        IggyErrorCode.InvalidTopicId => true,
        IggyErrorCode.InvalidReplicationFactor => true,
        IggyErrorCode.InvalidPartitionsCount => true,
        IggyErrorCode.InvalidSegmentSize => true,
        IggyErrorCode.InvalidMessagesCount => true,
        IggyErrorCode.InvalidHeaderKey => true,
        IggyErrorCode.InvalidHeaderValue => true,
        IggyErrorCode.InvalidMessagePayloadLength => true,
        IggyErrorCode.InvalidMessageChecksum => true,
        IggyErrorCode.InvalidKeyValueLength => true,
        IggyErrorCode.InvalidSegmentsCount => true,
        IggyErrorCode.InvalidIndexesByteSize => true,
        IggyErrorCode.InvalidIndexesCount => true,
        IggyErrorCode.InvalidMessagesSize => true,
        IggyErrorCode.InvalidOffset => true,
        IggyErrorCode.InvalidConsumerGroupId => true,
        IggyErrorCode.InvalidConsumerGroupName => true,
        IggyErrorCode.InvalidConnectionString => true,
        _ => false
    };

    /// <summary>
    ///     Tries to convert an integer status code to <see cref="IggyErrorCode" />.
    /// </summary>
    /// <param name="statusCode">The integer status code.</param>
    /// <param name="errorCode">The resulting error code if conversion succeeds.</param>
    /// <returns>True if the conversion succeeded, false otherwise.</returns>
    public static bool TryFromStatusCode(int statusCode, out IggyErrorCode errorCode)
    {
        if (Enum.IsDefined(typeof(IggyErrorCode), statusCode))
        {
            errorCode = (IggyErrorCode)statusCode;
            return true;
        }

        errorCode = IggyErrorCode.Error;
        return false;
    }

    /// <summary>
    ///     Converts an integer status code to <see cref="IggyErrorCode" />.
    ///     Returns <see cref="IggyErrorCode.Error" /> if the code is not recognized.
    /// </summary>
    /// <param name="statusCode">The integer status code.</param>
    /// <returns>The corresponding error code or <see cref="IggyErrorCode.Error" /> if not found.</returns>
    public static IggyErrorCode FromStatusCode(int statusCode)
    {
        return TryFromStatusCode(statusCode, out var errorCode) ? errorCode : IggyErrorCode.Error;
    }
}
